CoffeeW8.description.pdf: CoffeeW8.description.tex
	pdflatex CoffeeW8.description.tex
	pdflatex CoffeeW8.description.tex
	
clean :
	rm -f *.aux *.toc *.log *.out

clean-all :
	make clean
	rm -f *.pdf *.dvi 

